### ISSUE TITLE
Exportación a archivo LIMS

### ISSUE THREAD

**Issue by nolo11** [fundacion-sadosky/genis#3]
Agregar un booleano en los campos de exportación a archivo LIMS que indique si el perfil fue subido a la instancia superior.

**Comment by javieriserte** [comment]
Exported Lims files were modified to include fields that indicate that the profiles has been uploaded to a superior instance.

There are two types of Lims files exported.

- The created profiles.
- The matching profiles.

For the created profiles file, a new field named "Uploaded to Superior Instance".

Here there is an example of this kind of file:

    Sample Name	GENis code	Status	DateTime	Uploaded to Superior Instance
    BM23-28-93-E 	AR-C-SHDG-1119	INGBD	28/06/2023 05:01:10 PM	false
    BM23-28-94-E 	AR-C-SHDG-1120	INGBD	28/06/2023 05:01:10 PM	false
    Lab01	AR-C-SHDG-1100	INGBD	28/06/2023 05:28:17 PM	true

For the matching profiles file, two fields were added named "Sample Profile Uploaded to Superior Instance" and "Matched Profile Uploaded to Superior Instance".

Here there is an example of this kind of file:

    MatchId	Sample GENis Code	Sample Name	MatchedSample GENis Code	MatchedSample Name	status	Datetime	Sample Profile Uploaded to Superior Instance	Matched Profile Uploaded to Superior Instance
    649c918d265f4b4cc799e88f	AR-C-SHDG-1102	BM23-28-117-E 	AR-C-SHDG-1104	BM23-28-124-E 	Pending	28/06/2023 05:01:17 PM	true	false
    649c918e265f4b4cc799e891	AR-C-SHDG-1103	BM23-28-179-E 	AR-C-SHDG-1104	BM23-28-124-E 	Pending	28/06/2023 05:01:18 PM	false	false
    649c918e265f4b4cc799e892	AR-C-SHDG-1103	BM23-28-179-E 	AR-C-SHDG-1102	BM23-28-117-E 	Pending	28/06/2023 05:01:18 PM	false	true
    649c918f265f4b4cc799e893	AR-C-SHDG-1107	BM23-28-26-R	AR-C-SHDG-1101	BM23-28-126-E 	Pending	28/06/2023 05:01:19 PM	false	false

**Comment by javieriserte** [comment]
The files were modified mainly in this issue were:

- app/profile/ExportLimsFilesFilter.scala
- app/profile/FilesToLimsExporter.scala
- app/profile/LimsArchivesExporterService.scala

Also, the following files were modified to increase readbility, but no modifications to the business logic were introduced.

- app/assets/javascripts/common/services/cryptoService.js
- app/assets/javascripts/search/searchService.js
- app/assets/javascripts/stats/statsController.js
- app/controllers/Profiles.scala
- app/controllers/SearchProfileDatas.scala
- app/profile/Profile.scala
- app/profile/ProfileService.scala
- app/profiledata/ProfileDataRepository.scala
- app/profiledata/ProfileDataSearch.scala
- app/search/FullTextSearchService.scala
- app/security/AuthService.scala

The details of the modified lines can be viewed in the commit [b6caecd](https://github.com/fundacion-sadosky/genis/commit/b6caecdedbe99fe841f935965849d9aee9dd8d47).
