### ISSUE TITLE
Bug in DVI: Automatic result grouping throws an error.

### ISSUE THREAD

**Issue by javieriserte** [fundacion-sadosky/genis#56]
Summary of the issue:

    El problema se presenta en la agrupación automática que no muestra los resultados tirando un error.

    Le das agrupación automática, se lanza pero luego no muestra nada y se va de paseo.

The error message is:

    [error]- 2023-10-17 17:48:18,947 - play - Cannot invoke the action, eventually got an error: java.util.NoSuchElementException: None.get
    [error]- 2023-10-17 17:48:18,949 - application -

    ! @839632mnm - Internal server error, for (POST) [/user-matches-group] ->

    play.api.Application$$anon$1: Execution exception[[NoSuchElementException: None.get]]

**Comment by nolo11** [comment]
The matches repository is querying the wrong collection, the match is searched in the matches collection instead of the collapsingMatches collection.

**Comment by nolo11** [comment]
When the 'automatic grouping' process finishes, the results are not  displayed but rather a notification is generated. When you reload the tab, the results appear and you can access the details of each match.
