### ISSUE TITLE
Error on forensic search results.

### ISSUE THREAD

**Issue by javieriserte** [fundacion-sadosky/genis#64]
After getting a match in forensic module:

![image](https://github.com/fundacion-sadosky/genis/assets/476740/fd05b748-c2d4-476a-8569-1bf7678dc811)

if you try to view all results from a hit an error is raised:

![image](https://github.com/fundacion-sadosky/genis/assets/476740/82e74533-b506-496a-8ee8-00ea651dfb26)

**Comment by nolo11** [comment]
The canUploadMatchStatus method of the MatchingServiceSparkImpl class was parameterized to search for the correct match collection and the getMatchesByGroup method of the same class now uses the search criteria provided by the view when invoking it.
